### PR TITLE
Add justHere, justThere and co.

### PR DESCRIPTION
**Pull request by maxigit**

### CODE REVIEW

**Comment by phadej** [comment]
I added `justHere` and `justThere`, but for the rest I'll rather go for #101. `lens` vocabulary already makes it all possible, and duplicating everything would clutter the single module. Therefore I'll split it in the next major version.

**Comment by maxigit** [comment]
You can do the other by combining lenses, but the others are handy if you don't want to use lens at all. However, I understand the argument against it and it is only my opinion.

**Comment by phadej** [comment]
See `Data.These.Combinators` in http://oleg.fi/haddocks/these/

**Comment by maxigit** [comment]
Sorry, I misunderstood the comment.

**Comment by phadej** [comment]
updated the comment

**Pull request closed without merging**
