### PR TITLE
WIP: Added 'Partitionable' superclass to 'Align'.

### PR DESCRIPTION
**Pull request by ElvishJerricco**
**Forward:** I'm aware this is a massively breaking change. I understand if this isn't a road we want to go down.

---

`Partitionable` represents `fmapMaybe`, which happens to be equivalent to some convenient extra functions.

``` haskell
class Functor f => Partitionable f where
  cover :: (a -> These b c) -> f a -> (f b, f c)
  cover f as = ( fmapMaybe (these Just nothing (\a _ -> Just a) . f) as
               , fmapMaybe (these nothing Just (\_ b -> Just b) . f) as)
    where nothing _ = Nothing

  partitionMap :: (a -> Either b c) -> f a -> (f b, f c)
  partitionMap f = cover (either This That . f)

  fmapMaybe :: (a -> Maybe b) - f a -> f b
  fmapMaybe f = fst . partitionMap (maybe (Right ()) Left . f)
```

`Partitionable` is a categorical superclass of `Align`. `Align` represents lax monoidal functors from `Kleisli Maybe` to `Hask`. This means they are functors between these categories, necessitating the existence of `fmapMaybe`. As it turns out, `fmapMaybe` is equivalent to the more practically useful `cover` and `partitionMap` functions. And in fact, I suspect implementing `fmapMaybe` in terms of `cover` will usually perform better than implementing `cover` in terms of `fmapMaybe`.

The behavior of `partitionMap` is perhaps obvious. You form two new structures according to which positions return `Left` and which returned `Right`. It's virtually the same as [`partition` from `Data.List`](https://hackage.haskell.org/package/base-4.9.0.0/docs/Data-List.html#v:partition). But `cover` is less obvious. It forms a [covering](https://en.wikipedia.org/wiki/Cover_%28topology%29) of the input structure. That is, the union of the two output structures will have the same shape as the input, but they are not necessarily disjoint. They may overlap arbitrarily. This is a fairly powerful function. It is strictly more powerful than `unalign`, and represents an efficient method for breaking structures into filtered parts.

**EDIT:** To be clear, this pull request does change the class head for `Align`.

``` haskell
class Partitionable f => Align f where
  ...
```

---

Furthermore, this brings into question the `Unalign` class, which seems to be a strictly weaker version of `Partitionable`. The laws of `unalign` suggest that both outputs have the same shape, making it hardly more useful than `fmap`. However, `cover` and `partitionMap` are designed to tear down the shape; something `fmap` can never do. It would appear that `Unalign` exists solely for the sake of performance as a means of avoiding doing two traversals. I would argue that the same performance benefits are achieved with this definition, as long as `cover` is implemented with the same performance optimization in mind.

``` haskell
unalign :: Partitionable f => f (These a b) -> (f (Maybe a), f (Maybe b))
unalign = cover $ \ths -> case ths of
  This a -> These (Just a) Nothing
  That b -> These Nothing (Just b)
  These a b -> These (Just a) (Just b)
```

As such, perhaps `unalign` should be a member of `Partitionable`, with this default definition? Or else I think it should lose its class and become constantly defined in terms of `cover`.

---

**NOTE:** This pull request is a WIP. I am not confident enough in my understanding of `Stream` or `Bundle` to attempt to implement their instances. Assistance with this would be appreciated.

### CODE REVIEW

**Comment by ElvishJerricco** [comment]
Actually, I think `cover` can be a little more general. It strongly resembles this function:

```haskell
fcover :: Functor f => (a -> (b, c)) -> f a -> (f b, f c)
fcover f a = (fmap (fst . f) a, fmap (snd . f) a)
```

The function passed in is a morphism in Hask from `a` to Hask's product type over `b` and `c`, and the function return is a morphism of a similar form, also in Hask. It would make sense that this abstracts to any functor from a category with a [product](https://en.wikipedia.org/wiki/Product_(category_theory)) to Hask (or something more general than Hask, but I haven't figured that out yet). So, given a category and its product *(C, •, cfst, csnd)*, `cover` could look like this:

```haskell
class (Category c, Category d) => Functor c d f where
  fmap :: c a b -> d (f a) (f b)

cover :: Functor C (->) f => C a (b•c) -> (f a -> (f b, f c))
cover f a = (fmap (cfst . f) a, fmap (csnd . f) a)
```

Plugging *(`Kleisli Maybe`, `These`, `justThis`, `justThat`)* in for *(C, •, cfst, csnd)* yields:

```haskell
cover :: Partitionable f => (a -> Maybe (These b c)) -> f a -> (f b, f c)
cover f a = (fmapMaybe (justThis <=< f) a, fmapMaybe (justThat <=< f) a)
```

Which greatly simplifies how to define the laws for `cover`. The laws for `cover` as it stands would be an incomprehensible mess, which I'm having trouble even writing.

```haskell
fst . cover (Just . This) = id
snd . cover (Just . That) = id

cover (g <=< justThis <=< f) = cover g . fst . cover f
cover (g <=< justThat <=< f) = cover g . snd . cover f
```

So this representation solidifies `cover`'s relation to `fmapMaybe`, while making the laws clearer. But it somewhat changes the semantic meaning of `cover`, in a way that makes it obvious how arbitrary it is. It's just `fmap` of some form, applied twice. This is nice, but the main point of `cover` is to allow an instance to optimize it, and it's only an optimization for splitting a structure in *two*. If you want to split something into tenths, `cover` only helps you negligibly.

---

So I guess the point is that this raises questions about the usefulness of `cover`. Maybe `Partitionable` should just have `fmapMaybe`? In which case, `cover` and `partitionMap` would be utility functions in the module.

**Comment by phadej** [comment]
I don't understand all of the abstract nonsense here. How `Partionable` is related to `Align`, any law between `fmapMaybe` and `align`/`nil`

Also, isn't partionable same as https://hackage.haskell.org/package/witherable or https://hackage.haskell.org/package/filtrable

**Comment by ElvishJerricco** [comment]
It is definitely the same as `Filtrable`. Hadn't seen that. Though `Witherable` is a bit stronger, implying `Traversable`. Not sure if all `Partitionable`s are `Traversable`, but I would doubt it.

You can't define `fmapMaybe` in terms of `Align`, so it's not as strictly a superclass to `Align` as `Functor` is to `Applicative`. But `Align` does show symptoms of being `Partitionable`. `nil` proves that there is a version of the structure with no shape, so it makes sense that you should be able to filter out parts of the shape with `fmapMaybe`. `Align` generally represents the malleability of the shape of a structure, but it's only letting you *add* shape. Removing shape (`fmapMaybe`) is a natural implication.

It's mostly a consequence of category theory though. `Align` represents lax monoidal functors from `Kleisli Maybe` to `Hask`. In other words, `Align` is a theoretical equivalent to `Applicative`, just with a different category (actually slightly weaker than `Applicative` but that's not the point). `Applicative` is a subclass of `Functor` because in theory, applicatives come from functors. Similarly, `Align` categorically comes  from functors from `Kleisli Maybe` to `Hask`.

In fact, `nil` is only correct because of the relationship with `fmapMaybe`. Theoretically, lax monoidal functors only have `() -> f ()`, aka `f ()`, which is what `nil` represents. So you can't actually make that into `f a` for any `a` (as `nil` does) unless you can use `fmapMaybe (const Nothing)` on it. So `nil` would be incorrect, and much less useful, if it weren't for the categorical relationship with `fmapMaybe`.

**Comment by ElvishJerricco** [comment]
One law would be `fmapMaybe (const Nothing) = const nil`

**Comment by phadej** [comment]
This got me thinking that there are containers which can has `align`, but cannot have `nil`.
E.g. `NonEmpty`. So we'd need to split the hierarchy, similarly as there are `Apply` + `Alternative`, into `Align` + *align + nil* or *just align* + `Align`. I'd pick first one, i.e move `nil` into other class.

But how hierarchy would look like then. With new `Align` as

```haskell
class Functor f => Align f where
    align :: f a -> f b -> f (These a b)
    -- no `nil`!
```

`Partionable`, `Filtrable`, or `Witherable` cannot be a superclass of this.

I'm ok pursuing the refactor (this isn't core package!), if we get good story.

**Comment by ElvishJerricco** [comment]
`Apply` represents semigrouping functors between semigroupoids, ultimately just meaning the preservation of products. To draw a parallel between `Apply` and `Align` without `nil`, we're still preserving the products `(,)` and `These`. So our category is still `Kleisli Maybe`, and thus our functors still map `a -> Maybe b` to `f a -> f b`.

So I guess it's just a question of if we'd rather have a nice piece of category theory which implies the very useful `fmapMaybe`, or have more instances of the `align` function.

**Comment by ElvishJerricco** [comment]
To put this more conceptually, `Align` represents functors with "positions" for values to go in. `These` is used because either argument maybe contain positions that the other doesn't. The fact that positions are apparently allowed to be absent, and that there's no indication that any position must be present, suggests that we should have the power to make positions become absent, just as we have the power to make positions become present with `align`.

**Comment by ElvishJerricco** [comment]
As a motivating example, consider an alignment of maps, and imagine we want to align with something to remove elements from the maps.

```haskell
remove :: Align f => f k -> f (Map k b) -> f (Map k b)
remove = alignWith $ \case
  This _ -> Map.empty
  That map -> map
  These k map -> Map.delete k map
```

Really, we want this to be able to eliminate all empty maps.

```haskell
alignWithMaybe :: Align f => (These a b -> Maybe c) -> f a -> f b -> f c
alignWithMaybe f as bs = fmapMaybe id $ alignWith f as bs

remove :: Align f => f k -> f (Map k b) -> f (Map k b)
remove = alignWithMaybe $ \case
  This _ -> Nothing
  That map -> map
  These k map -> let
    remaining = Map.delete k map
    in if null remaining
      then Nothing
      else remaining
```

**Comment by ElvishJerricco** [comment]
We could also get an applicative-like operator if we had `fmapMaybe`.

```haskell
(<@>) :: Align f => f (a -> b) -> f a -> f b
(<@>) = alignWithMaybe $ these (const Nothing) (const Nothing) (\f a -> Just $ f a)
```

Without `fmapMaybe`, this would have to return `f (Maybe b)`.

**Comment by phadej** [comment]
Hmm, I have to rethink this once again. Let's see if I'll have some time during Christmas holidays

**Comment by ElvishJerricco** [comment]
Yea I need to think about this too. For one thing, I don't think `nil` is actually correct for the category theory. So I need to figure out how to reconcile that, since `nil` is fairly important. Also, it really should just be `fmapMaybe`; none of this `cover` crap.

**Comment by phadej** [comment]
I think that `Align` is too powerful. E.g. `V2` (or `Pair` from `uniform-pair`) can have `align`, but cannot have
`nil` (neither `fmapMaybe`).

It might make sense to split `nil` out of `Align`. If there is some categorical explanation to this, I'd like to hear it.

**Comment by ElvishJerricco** [comment]
Well the presence of `nil` suggests the possibility of the structure being empty, even though there's no way currently to approach emptiness. In terms of theory, it makes as much sense to separate `nil` from `align` as it does to separate `<*>` from `pure` (which is something a lot of people like; look at PureScript's `Monad` hierarchy). So I think that's fine. But there's just no categorical explanation for having `align` without `fmapMaybe`.

FWIW, the problem with `nil` that I mentioned above is that the theory for monoidal functors dictates the need for `() -> f I`, where `I` is the monoidal identity type in `Kleisli Maybe`. I was trying to think of choices for `I` that explains how `f I` is isomorphic to `forall a. f a` (that is, `nil`). And I think I have found one. The problem with `()` is that there needs to be an isomorphism between `a` and `These a I`, but the morphism from `a -> These a ()` has two possible outputs, meaning it wouldn't be an isomorphism. `Void`, however, ensures that `These a Void` can only ever be `This a`, which makes the isomorphism trivial. Finally, this means the "correct" type for `nil` is `() -> f Void`, which I believe is the same thing as `forall a. f a`, because `forall a. a` and `Void` are equally uninhabitable.

**Comment by phadej** [comment]
The hierarchy have been reworked in `0.8` and will again in `1`. `Partionable` doesn't seem to fit into the picture.

If you disagree, and see how it can be fit, please open an issue.

**Pull request closed without merging**
