### PR TITLE
Define Align instance for HashMap

### PR DESCRIPTION
**Pull request by sjakobi**

### CODE REVIEW

**Comment by jwiegley** [comment]
@sjakobi Since HashMaps come in both strict and lazy flavors, can you provide instances for both, using qualified name to distinguish the two?

**Comment by sjakobi** [comment]
Like this?

```haskell
import qualified Data.HashMap.Lazy as HML
import qualified Data.HashMap.Strict as HMS


instance (Eq k, Hashable k) => Align (HML.HashMap k) where
    nil = HML.empty
    align m n = HML.unionWith merge (HML.map This m) (HML.map That n)
      where merge (This a) (That b) = These a b
            merge _ _ = oops "Align lazy HashMap: merge"

instance (Eq k, Hashable k) => Align (HMS.HashMap k) where
    nil = HMS.empty
    align m n = HMS.unionWith merge (HMS.map This m) (HMS.map That n)
      where merge (This a) (That b) = These a b
            merge _ _ = oops "Align strict HashMap: merge"

```

This results in the following error message:
```
/home/simon/src/these/Data/Align.hs:194:10:
    Duplicate instance declarations:
      instance (Eq k, Hashable k) => Align (HMS.HashMap k)
        -- Defined at Data/Align.hs:194:10
      instance (Eq k, Hashable k) => Align (HMS.HashMap k)
        -- Defined at Data/Align.hs:200:10
```

I believe the reason is that both flavors use [this definition in `Data.HashMap.Base`](https://hackage.haskell.org/package/unordered-containers-0.2.5.1/docs/src/Data-HashMap-Base.html#HashMap).

It seems that the only way to get instances in both flavors would be to put them in separate modules.

Thoughts?

**Comment by phadej** [comment]
Those orphan instances would be too easy to mix.

I'd just have lazy variant, the same way as with `Map`.

**Comment by jwiegley** [comment]
I'll defer to @isomorphism on this decision, since he was the original designer.

**Comment by isomorphism** [comment]
Providing conflicting orphan instances sounds migraine-inducing, ahaha.

Ok, so just to make sure I understand this correctly: 

* There's one `HashMap` type, and the strict/lazy modules differ only in the behavior of the functions
* The `These` constructors in the result are created by the `Align` instance and will never be bottom
* The "strict" variant will force the `These` constructors and will not force any value in the input hashmaps

If so, I really don't see any benefit whatsoever to using the lazy version. No meaningful computation could be contained in the resulting thunk since the only information provided by the `These` constructors is which of the original maps an entry came from, which is obviously already known.

**Comment by sjakobi** [comment]
I have updated the PR to use `Data.HashMap.Strict` instead of `Data.HashMap.Lazy`.

**Pull request merged**
